title: Ahmet PAYASLIOĞLU
description: "Siber Güvenlik ve Adli Bilişim konuları üzerine paylaşım yaptığım kişisel bloğum."
author:
  name: "AhmetPayaslioglu"
  email: "someone@somewebsite.somedomain"
  url: "https://ahmetpayaslioglu.github.io/"
baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "AhmetPayaslioglu"
year : "2020"
google_analytics: [UA-186298091-1]
